### ISSUE TITLE
MAC版，同时安装Nginx和Caddy，在站点中设置不同端口。Nginx访问有问题

### ISSUE THREAD

**Issue by hb2013** [xpf0000/PhpWebStudy#100]
同时安装Nginx和Caddy，在站点中设置不同端口。Nginx访问有问题，也能访问，但是显示空白。Caddy可以访问。如果Caddy停掉，Nginx就正常了

**Comment by xpf0000** [comment]
本地测试未发现问题

Nginx 设置端口 8080  Caddy 设置端口 8081

启动 Caddy 和 Nginx

使用域名+端口号访问

Nginx: http://www.lvtest.com:8080

Caddy: http://www.lvtest.com:8081

**Comment by hb2013** [comment]
我是Nginx 设置端口 80  Caddy 设置端口 8080
访问有问题，是两个都不能设置80？

**Comment by xpf0000** [comment]
Nginx 和 Caddy 同时启动的话. 两边的端口号不能重复. 否则会有冲突.
