### ISSUE TITLE
怎么安装PDO_PGSQL扩展？

### ISSUE THREAD

**Issue by hb2013** [xpf0000/PhpWebStudy#101]
在PHP安装扩展那里，就没有这个扩展，这个应该也比较常用吧？

**Comment by xpf0000** [comment]
你用的啥系统? mac? win?

如果是 mac

1. Homebrew 安装的php. 编译时已经内置了 pgsql 支持了 无需再单独安装扩展

2. Macports 安装的 php. 可以在扩展里找到 postgresql. 安装即可

可以用以下代码简单测试:

```php
<?php
$conn_string  =  "host=localhost port=5432 dbname=postgres user=root password=postgres" ;
$dbconn = pg_connect($conn_string);
if (!$dbconn)
    echo "Fail !!!";
else
    echo "Success !!!";
pg_close($dbconn);

phpinfo();
```

**Comment by hb2013** [comment]
感谢，我用Homebrew重新装了下PHP。我再问下，PG数据库能不能带上pgvector这个插件，这个安装都是git下载在后make。我这make不过去。

**Comment by xpf0000** [comment]
1. 你可以下载官方 Postgres.app https://postgresapp.com/downloads.html  这个默认包含了pgvector插件. 下载完后. 在桌面或其他位置 创建一个替身文件 指向 /Applications/Postgres.app/Contents/Versions/16  然后在PhpWebStudy的Postgresql 模块中, 添加自定义版本路径 选择这个替身文件. 这样就可以使用pgvector了

2. 使用Homebrew 和 Macports 安装的版本, 目前可以使用以下方法安装. 后续会考虑做成一键安装

创建个 sh 文件, 内容如下:

```sh
#!/bin/zsh
## Macports 路径替换为自己的
export PGROOT="/opt/local/lib/postgresql14"
export PATH="/opt/local/lib/postgresql14/bin:$PATH"
## Homebrew 路径替换为自己的
#export PGROOT="/usr/local/Cellar/postgresql@16/16.3"
#export PATH="/usr/local/Cellar/postgresql@16/16.3/bin:$PATH"
cd /tmp
sudo rm -rf pgvector
git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git
cd pgvector
sudo make
sudo make install
sudo rm -rf pgvector
```

执行此文件进行安装

**Comment by hb2013** [comment]
非常感谢，我用第一种方法解决了，只要PG可以用就行。添加自定义版本路径启动不了。不过自带的真的自带pgvector插件。谢谢，第二种方法我是make出错，不能继续。再次感谢
