### ISSUE TITLE
mac brew 安装 出现 SHA256 mismatch错误

### ISSUE THREAD

**Issue by 35598253** [xpf0000/PhpWebStudy#102]
brew install phpwebstudy
Downloading https://github.com/xpf0000/PhpWebStudy/releases/download/v4.1.0/
Already downloaded: /Users/marc/Library/Caches/Homebrew/downloads/872088b6dce018d6894d7db50c80b6acea2de2fd708ab05f43eef242ff9e1aae--PhpWebStudy-4.1.0-arm64-mac.zip
Error: SHA256 mismatch
Expected: c695641943aa9eefa9ce08a46cda46edcdd71a2e3e9d7ebe6895ca6483b462d7
  Actual: ba02b4e4e66f5e7f48c2d60968836326c84a9f3cf060b6747c66b88002cec5d5
    File: /Users/marc/Library/Caches/Homebrew/downloads/872088b6dce018d6894d7db50c80b6acea2de2fd708ab05f43eef242ff9e1aae--PhpWebStudy-4.1.0-arm64-mac.zip
To retry an incomplete download, remove the file above.

brew 安装出现此错误

brew是重新安装的，macos 14.6.1

**Comment by xpf0000** [comment]
这个是我的问题,  brew拉取过升级版本信息后我又上传了个新的, 但是没升级版本号. 导致信息对应不上

新版已发布. 不会有这个问题了
