### ISSUE TITLE
Issue Dtrabase and Phpmyadmin ( Windows Verison )

### ISSUE THREAD

**Issue by re-LIF3** [xpf0000/PhpWebStudy#103]
Windows Version:

MariaDB not working ( user root  pass: root )

MariaDB and Mysql very slow for access Phpmyadmin

**Comment by xpf0000** [comment]
1. Use PhpWebStudy to download and start Mariadb. The database folder will be initialized during the first startup. And initialize the user adn password as root root. If the first attempt fails to start successfully. Send out the log information

2. The problem of slow of phpMyAdmin. Copy config.sample.inc.php to config.inc.php and modify

```php
$cfg['Servers'][$i]['host'] = 'localhost';
```
to
```php
$cfg['Servers'][$i]['host'] = '127.0.0.1';
```

**Comment by xpf0000** [comment]
port: 3307  

modify mariadb's config file. change port from 3307 to 3306. then restart mariadb

**Comment by xpf0000** [comment]
1. If you use a VPN, try turning off the VPN first. Some VPN Apps will handle domain names. This causes this problem
2. Is there this domain name in the system hosts file?

**Comment by xpf0000** [comment]
1. Is PWS hosts enabled?

![8d6a-9cb16e397b1a](https://github.com/user-attachments/assets/259fbbc8-38ff-4dfa-a4d3-3dc5ac91bec6)

2. Is there this domain name in the system hosts file?

![899a-d4ff8aff3df3](https://github.com/user-attachments/assets/ff8b6423-ca36-44cf-8113-0e4fd7bcb91b)

3.  Is Apache start success?  if start success. conf file should includes this block in the file begin

![47c638e27bd](https://github.com/user-attachments/assets/6c37ca70-1bc7-4485-82bf-9f66952a4676)

4. Is conf file has this? this load all PWS's site vhost file.

![cc9780a3f8cd](https://github.com/user-attachments/assets/5043da13-cd61-4a10-8604-ca416832c852)

**Comment by xpf0000** [comment]
Have you commented out these two lines in site's vhost file?  This is required and cannot be commented.

![QQ_1724839800197](https://github.com/user-attachments/assets/0967874e-9f5f-46bc-95d7-b5efdad818da)

![QQ_1724839832219](https://github.com/user-attachments/assets/1d211cb7-ff4a-4ccb-8d95-e0f4955c787d)

**Comment by xpf0000** [comment]
There are many reasons why this problem occurs.  eg：

1. Add a .user.ini file to the project root directory

![QQ_1724985621265](https://github.com/user-attachments/assets/c3de07c1-d2e5-44ac-b80f-9515e23a0de0)

2. Set a wrong folder in the .user.ini file.

![QQ_1724985631534](https://github.com/user-attachments/assets/6fbea69f-01e3-429c-8eda-dea3ce941d98)

3. Restart php. then will get 'No input file specified.' issues

![QQ_1724839832219](https://github.com/user-attachments/assets/c0b45495-1b99-4ef3-a1fe-965049c338ea)

4. Site log has the error message

![QQ_1724985549087](https://github.com/user-attachments/assets/69b6d5db-966c-4688-92bc-606179c06e53)


https://www.alibabacloud.com/help/en/ecs/support/what-do-i-do-if-the-no-input-file-specified-error-is-returned-when-i-access-websites-deployed-on-an-ecs-instance

So, these are all configuration issues. Everyone's situation is different. These are not things that PWS can solve. The most effective way is to look at each log. Then follow the prompts to solve the problem
