### ISSUE TITLE
window版本的php的所有版本都没有redis扩展

### ISSUE THREAD

**Issue by lvxiaoyan** [xpf0000/PhpWebStudy#105]
window版本的php的所有版本都没有redis扩展，这一点很糟糕，
没办法公司只让用windows自配机器，还有就似乎无法安装pecl去添加扩展，挣扎了两天。很无力

**Comment by xpf0000** [comment]
1. redis扩展是可以做成一键下载安装，但是redis扩展是区分php版本的， 哪些PHP版本要使用什么版本的redis扩展。后续php版本更新了或者redis扩展版本更新了， 还需要更新。 很繁琐。 目前没有时间和精力。

2. 软件里已经给出了扩展下载站点和扩展文件夹， 手动下载dll文件， 放到扩展文件夹里。 配置文件里启用下就行了

![QQ_1725003247581](https://github.com/user-attachments/assets/a4214689-a7aa-4470-9399-a4e9e0dd1b67)

https://pecl.php.net/package/redis

![QQ_1725003607396](https://github.com/user-attachments/assets/26b15734-33cf-4175-8af3-de74dcedbe00)
