### ISSUE TITLE
Windows: Add to path does not seem to work

### ISSUE THREAD

**Issue by vesper8** [xpf0000/PhpWebStudy#108]
Hi!

I've installed 4.2 on Windows and set up all the services. I added a host. Added php, mysql, composer.

I would like to run composer install now, or php artisan, but both commands fail because they can't find the binaries.

I've clicked on 'add to path' from the context menu inside PhpWebStudy. I've clicked on this many times, for PHP, for composer, for mysql.. and yet even after restarting the terminal, they are still not available on the path

Running `echo $env:PATH -split ';' in the terminal does not display them either.

Any idea what is going on?

Many thanks

**Comment by xpf0000** [comment]
There are currently some problems with this function. You need to manually add the path to PATH currently. A new version will be released soon to fix it.

**Comment by xpf0000** [comment]
Thank you for your feedback. The latest version has fixed this issue.
