### ISSUE TITLE
Composer does not work on windows

### ISSUE THREAD

**Issue by nedaeidev** [xpf0000/PhpWebStudy#109]
After installing Composer, a folder will be created in which only the main file of Composer is located.
This file cannot be used alone for Windows and there must be a bat file with the same name in the folder, so that after adding the folder path to the system path, Windows can run the Composer.
Now we have access to composer out of the box as a command line.

tested with PhpWebStudy v4.2

Please add the bat file (composer.bat) with the following content in the Composer-x.x.x folder:

@echo off
php "%~dp0composer.phar" %*

**Comment by nedaeidev** [comment]
"add to path" menu action work for me

if you want to run composer you must create a file in below URI and it's name should be composer.bat
C:\Users\xxx\AppData\Local\Programs\PhpWebStudy-Data\app\composer-2.7.8\composer.bat
then add below code in to composer.bat

# begin code:

@echo off
php "%~dp0composer.phar" %*

# end code

now composer command work on cmd and power shell

**Comment by nedaeidev** [comment]
> I've manually added php to the system environment variables because the "add to path" menu action doesn't seem to work on Windows.
> 
> I was then able to run composer like this:
> 
> php C:\Users\xxx\AppData\Local\Programs\PhpWebStudy-Data\app\composer-2.7.8\composer.phar install
> 
> But then I ran into issues because some php extensions are missing

"add to path" menu action work for me

if you want to run composer you must create a file in below URI and it's name should be composer.bat
C:\Users\xxx\AppData\Local\Programs\PhpWebStudy-Data\app\composer-2.7.8\composer.bat
then add below code in to composer.bat

begin code:
@echo off
php "%~dp0composer.phar" %*

end code
now composer command work on cmd and power shell

**Comment by xpf0000** [comment]
Thank you for your reminder. The lasted version has fixed this issues. composer.bat will auto create when composer install or add to path.

**Comment by nedaeidev** [comment]
Thank you for fix it.
