### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by f3liiix** [xpf0000/PhpWebStudy#115]
![screenshot-20240908-210009](https://github.com/user-attachments/assets/93926e0a-8672-4d60-8e7d-7a900d722059)

系统已经装了 homebrew，可是软件却提示未检测到。

另外，这个界面上的url是404

**Comment by xpf0000** [comment]
```sh
eval $(/opt/homebrew/bin/brew shellenv) #ckbrew
```
替换里面的brew路径为你电脑上的路径. 然后添加这个到 ~/.zsh 或者 ~/bash_profile 文件里 

后续会再优化下

**Comment by f3liiix** [comment]
> ```shell
> eval $(/opt/homebrew/bin/brew shellenv) #ckbrew
> ```
> 
> 替换里面的brew路径为你电脑上的路径. 然后添加这个到 ~/.zsh 或者 ~/bash_profile 文件里
> 
> 后续会再优化下

依然不行

**Comment by hao-888** [comment]
我这也不行，问题一样，没更新新版本之前还行

**Comment by xpf0000** [comment]
最新版已处理
