### ISSUE TITLE
call version.bat<br/>Error: Command failed: call version.bat

### ISSUE THREAD

**Issue by KnightBlood** [xpf0000/PhpWebStudy#119]
![image](https://github.com/user-attachments/assets/663526f5-04c8-452f-bc1b-6bac8356f21f)

**Comment by KnightBlood** [comment]
我觉得 tomcat默认用的jdk 应该是phpwebstudy里面下载jdk，不太想把什么都往系统环境变量里面放，容易搞坏环境变量

**Comment by xpf0000** [comment]
1. 报错是因为没检测到JAVA环境   JAVA_HOME/JAR_HOME 未找到
2. java环境可以在 PWS的Java面板里下载和设置.
