### ISSUE TITLE
Does not find brew installed versions

### ISSUE THREAD

**Issue by ejunker** [xpf0000/PhpWebStudy#120]
I just upgraded to version 4.3.1 and it lost all my configuration. I go to the PHP tab and I click the reload button but it cannot find my installed version of PHP. I installed PHP using the standard Homebrew location.

```
❯ which php
/opt/homebrew/bin/php
```

I go to settings and try to change Brew Source Switch to Default but I get an error that just says "Failed".  I am using macOS Sonoma 14.7

I tried to manually add the path of `/opt/homebrew/bin` but it still did not find a php version to use.

**Comment by xpf0000** [comment]
Have you changed your computer password?  If you have, you need to change it in PWS Settings->Reset Computer Password

**Comment by ejunker** [comment]
@xpf0000 yes, I did change my password. I updated my password in PWS and now it works. Thanks! You should try to improve the error messages for when that happens.
