### ISSUE TITLE
在设置中的电脑密码选项，建议加密

### ISSUE THREAD

**Issue by C4skg** [xpf0000/PhpWebStudy#122]
这里的密码可直接查看明文，感觉不太安全
![QQ_1726746831697](https://github.com/user-attachments/assets/5fab1fad-a6b9-40af-b794-530aa5c2744e)

**Comment by xpf0000** [comment]
恩 查看密码那里考虑加个密码验证,  弹窗让用户输入密码. 正确才显示

**Comment by xpf0000** [comment]
最新版已处理. 可以更新看下

**Comment by C4skg** [comment]
感谢
