### ISSUE TITLE
东西非常好用,但是homebrew发现了一个bug

### ISSUE THREAD

**Issue by SwpuEsine** [xpf0000/PhpWebStudy#123]
我以为我的电脑坏了,我homebrew安装的是5.0.8
<img width="1091" alt="截屏2024-09-24 上午7 33 01" src="https://github.com/user-attachments/assets/c40e4eb9-868f-4441-b905-f21a9854ce5b">
然后你的软件显示的是7版本
<img width="1013" alt="截屏2024-09-24 上午7 33 47" src="https://github.com/user-attachments/assets/387a3c79-40ab-4c7c-80a7-1e973f11d88a">
并且我在redis-cli 启动redis的时候,你的软件显示我没有启动 没有检测到

**Comment by xpf0000** [comment]
```
brew search redis
```
看下哪个安装了
```
brew info redis
```
看下详情. 里面有版本号

软件不检查用户自己启动的服务.  因为用的配置文件.日志保存位置和软件的不一样. 软件有自己的启动方式.

**Comment by SwpuEsine** [comment]
好的 谢谢
