### ISSUE TITLE
网站目录必须是你的那个lib下面的www目录吗,为什么我设置了自己的目录,我是thinkphp,设置后根本没有效果呢

### ISSUE THREAD

**Issue by SwpuEsine** [xpf0000/PhpWebStudy#124]
我搭建使用的代码是开源的 萤火商城。在宝塔可以 在本地想跑下跑不起来 不知道为什么
<img width="1091" alt="截屏2024-09-26 上午10 52 39" src="https://github.com/user-attachments/assets/7b533333-f150-43bf-85ac-8b3654f46f5f">

**Comment by SwpuEsine** [comment]
ip是解析对了 但是访问没有相应呢 ![Uploading image.png…]()

**Comment by xpf0000** [comment]
nginx url rewrite 配置了吗?  编辑最下面

**Comment by SwpuEsine** [comment]
https://gitee.com/xany/yoshop2.0。
<img width="1022" alt="截屏2024-09-26 上午11 06 20" src="https://github.com/user-attachments/assets/1b060e36-7797-4d66-b87e-733e2d6ec422">
我用的这个代码 我配置和取消都尝试了 还是不行呢,我试试你的www目录吧

**Comment by xpf0000** [comment]
我不清楚你怎么操作的. 我本次测试如下: 

1.  在用户目录下 git clone项目
```sh
cd ~ && git clone git@gitee.com:xany/yoshop2.0.git
```
2. 添加站点

![6af75af4caa7](https://github.com/user-attachments/assets/1d5b7aa7-1f9f-4bc0-bf3b-187ba7a26c9e)
![8702e690a3f9](https://github.com/user-attachments/assets/b4a1fa6b-559c-421a-896d-f16a2968a091)

3. 启动php 和 nginx
![1746afd77c29](https://github.com/user-attachments/assets/1ad26ea8-c32b-4dc5-944a-cb34744a6475)

可以正常访问站点.

**Comment by SwpuEsine** [comment]
好奇怪 我昨天搞了好久,我看看呢,我用的thinkphp的模板,然后我的路径也没空格,不过我没搞ssl，我试试这个

**Comment by xpf0000** [comment]
你可以执行下以下命令, 看下文件夹权限是否有问题
```sh
cd ~ && ls -al
```
正常是这样: 
![b21cdaceb534](https://github.com/user-attachments/assets/014bdb9c-430d-41ae-a414-12c13ebae264)

**Comment by SwpuEsine** [comment]
我这个软件不能折叠,不知道我的是不是老的版本,新的版本发布了吗,我是release下载的
<img width="1250" alt="截屏2024-09-26 上午11 24 06" src="https://github.com/user-attachments/assets/7f40ffb2-48cb-4286-8fe3-703959505be4">

**Comment by SwpuEsine** [comment]
drwxr-xr-x  25 jiwan  staff   800 Sep 24 06:45 yoshop2.0

**Comment by xpf0000** [comment]
如果开着 VPN 的话. 可以尝试先把 VPN 关了

**Comment by SwpuEsine** [comment]
感谢,确实代理问题

**Comment by unrelaxs** [comment]
我也是遇到同样问题，解决方法是：nginx多点击刷新按钮，让他重启下！

<img width="996" height="296" alt="Image" src="https://github.com/user-attachments/assets/26ae5ff0-05da-4f42-b244-8a6d05bf9b53" />
