### ISSUE TITLE
不能自定义数据或是扩展目录吗?

### ISSUE THREAD

**Issue by lifetin** [xpf0000/PhpWebStudy#126]
软件挺好挺全,就是不能自定义数据或是扩展目录吗?
C盘空间一盘都不大,软件是安装在C盘,结果好像不能自定义数据目录

**Comment by xpf0000** [comment]
你装的老版的吧. 现在数据目录是和安装目录同级别的. 安装到哪. 数据目录就在哪.

**Comment by lifetin** [comment]
新版本的. 看到了,这个暂时能解决问题.

另外一个问题

![image](https://github.com/user-attachments/assets/83d1ec6f-ce80-41cc-9b3a-01c2daf80a2b)
添加了一个自定义的Nginx目录. 后面在这列表删掉了,  结果它把我目录彻底删了.  这就出大问题了.原目录是已经在用的ng了, 配置都被删完了. 没办法跑起来了

**Comment by xpf0000** [comment]
额... 这块考虑不周全. 忘记用户自定义路径的问题了. 明天发个新版本. 后续不会再删除用户目录. 全部做软删除.

**Comment by lifetin** [comment]
尝试恢复,恢复不了, 被软件这块坑死了. 重新配置文件,本地一二个项目,几个小时都不一定完整还原.
删文件是个非常严谨的事情,没有任何提示删掉目录. 我也不知道该说什么了
