### ISSUE TITLE
windows版本安装后，发现redis，mysql有默认的配置，无法自定义

### ISSUE THREAD

**Issue by richwxd** [xpf0000/PhpWebStudy#128]
删不掉这些配置，做不到自定义

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by xpf0000** [comment]
为了软件能管理这些服务， 有些服务的配置项是从启动命令里写死的。 例如加载的配置文件。 配置文件里的日志路径和PID文件路径不要修改， 其他都可以素以修改。
