### ISSUE TITLE
macOS 13 测试版下会卡在「输入电脑密码」

### ISSUE THREAD

**Issue by JJYing** [xpf0000/PhpWebStudy#13]
好像其他需要电脑密码的 app 也有不少挂了的

**Comment by xpf0000** [comment]
能帮忙测试下吗? 这边没有13的系统
1. 应用菜单里 窗口->打开调试窗口  可以打开调试窗口 看下有什么提示
2. 命令行进入/Applications/PhpWebStudy.app/Contents/MacOS路径  然后 ./PhpWebStudy 运行 看下有什么提示
3. 输入电脑密码那里 最终检测密码是否正确执行的是这个命令:  echo '${pass}' | sudo -S chmod 777 /private/etc/hosts  可以用命令行执行下 看有什么提示

**Comment by JJYing** [comment]
哦……我发现密码输入没反应是因为我的密码是空格……改了普通字符就正常进去了，但是进去之后除了 PHP 其他几个都启动不了，提示信息是「Error: 启动文件不存在,服务启动失败」，然后调试窗口里没有其他特别的提示，用 2 里的方法进去似乎也是一样

**Comment by xpf0000** [comment]
密码问题是代码里把密码trim了, 没有考虑到密码里有空格的问题, 下次发新版会修复

php nginx这些启动时候, 首先需要在切换版本那里选择一个版本, 如果没有可用版本, 需要在版本管理里安装一个

在服务那个页面, 当前版本那里 会显示 版本号和此版本所在文件夹 , 正常如果这里都版本号和所在文件夹都显示, 理论上是可以启动的, 即使启动失败, 一般也都是配置文件问题,  根据错误提示, 基本都能解决

提示启动文件不存在的话, 可以复制服务那个页面里的版本所在文件夹, 打开看下是否有对应的启动文件, 各个应用的启动文件如下:

`{
apache: 'apachectl',
          nginx: 'nginx',
          php: 'php-fpm',
          mysql: 'mysqld_safe',
          memcached: 'memcached',
          redis: 'redis-server'
}`
