### ISSUE TITLE
apache如何配置伪静态

### ISSUE THREAD

**Issue by zzZxby** [xpf0000/PhpWebStudy#131]
apache如何配置伪静态呢，一直报无法访问.htaccess问题
![QQ_1728570133877](https://github.com/user-attachments/assets/1abba406-b575-4f61-927a-2c30943a738a)
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe
给文件权限也没解决，htaccess就放在网站对应目录下，请教各位大佬一下

**Comment by zzZxby** [comment]
macos 15.0.1系统

**Comment by xpf0000** [comment]
https://doc.thinkphp.cn/v8_0/url_access.html

**Comment by zzZxby** [comment]
> https://doc.thinkphp.cn/v8_0/url_access.html
![QQ_1728635672844](https://github.com/user-attachments/assets/f3dec0db-bdb0-4805-a77f-e2a1b569ae5a)
![QQ_1728635725719](https://github.com/user-attachments/assets/9225c185-3abc-4be6-aba1-71b670f2d1f2)
![QQ_1728635774137](https://github.com/user-attachments/assets/405c9cb5-dac9-4d88-818d-932ccffd6a5e)
三项配置都配置过了，网站仍然不能访问（htaccess文件为源码自带）
![QQ_1728635835416](https://github.com/user-attachments/assets/45793300-568a-4f86-9705-d1253a403464)

**Comment by zzZxby** [comment]
配置更改后，apache也重启过

**Comment by newnight** [comment]
AllowOverride All 配置的是项目目录还是默认 apache 的/usr/local/var/www ？
 
在自己的项目目录配置里，或者用虚拟主机：
<VirtualHost *:80>
    ServerName example.com
    ServerAdmin example@example.com

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>
    DocumentRoot /项目目录
    <Directory "/项目目录/">
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
        AllowOverride All
        Order allow,deny
        Allow from All
    </Directory>
    
    RewriteEngine On
    RewriteOptions Inherit
</VirtualHost>

然后重启试试

**Comment by zzZxby** [comment]
> AllowOverride All 配置的是项目目录还是默认 apache 的/usr/local/var/www ？
> 
> 在自己的项目目录配置里，或者用虚拟主机：
> 
> ```
> <VirtualHost *:80>
>     ServerName example.com
>     ServerAdmin example@example.com
> 
>     <FilesMatch \.php$>
>         SetHandler application/x-httpd-php
>     </FilesMatch>
>     DocumentRoot /项目目录
>     <Directory "/项目目录/">
>         DirectoryIndex index.php index.html index.htm default.php default.html default.htm
>         AllowOverride All
>         Order allow,deny
>         Allow from All
>     </Directory>
>     
>     RewriteEngine On
>     RewriteOptions Inherit
> </VirtualHost>
> ```
> 
> 然后重启试试

感谢，我本来使用的是系统自带的apache，然后我用brew在工具里下载了一个新的apache，网站就可以运行了
猜测应该是usr那个apache权限问题

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
