### ISSUE TITLE
服务无法正常启动

### ISSUE THREAD

**Issue by biiiiiigmonster** [xpf0000/PhpWebStudy#135]
平台：window
phpwebstudy：4.3.5
![image](https://github.com/user-attachments/assets/43b8593f-9ef5-4ac1-b7fb-7c0b0ee3a6e0)
![image](https://github.com/user-attachments/assets/a5edb178-544f-4b0d-87cd-5d0fa41d49a9)

**Comment by Nice-CareFree** [comment]
同样的问题

**Comment by xpf0000** [comment]
升级最新版再试下

**Comment by Nice-CareFree** [comment]
没问题了

> 升级最新版再试下
