### ISSUE TITLE
哈咯,基于nginx,hosts创建的站点能否设置不记录access日志?

### ISSUE THREAD

**Issue by catw0rld** [xpf0000/PhpWebStudy#16]
![image](https://user-images.githubusercontent.com/68625234/175763488-71ff46e6-0b7d-456f-afbc-5ecf41de36df.png)

**Comment by xpf0000** [comment]
目前可以手动配置站点的vhost实现  日志那里点打开  找到vhost文件夹 修改里面的配置文件
后续会新增打开编辑配置文件的功能
