### ISSUE TITLE
能否新增运行目录功能？

### ISSUE THREAD

**Issue by lilechao** [xpf0000/PhpWebStudy#2]
rt

**Comment by xpf0000** [comment]
现在不是能添加host吗? 那么就是每个站点的目录啊 这个具体是指什么功能?

**Comment by lilechao** [comment]
部分程序需要指定二级目录作为运行目录，如ThinkPHP5，Laravel 他的运行目录为public，而网站目录为public上层。 所以。。

**Comment by xpf0000** [comment]
这个创建host时候直接指定二级目录文件夹就行了吧  vhost的模板是拷贝的宝塔的 看了下 宝塔的二级目录应该就是直接改的站点root
或者使用url rewrite设定  nginx的话 在host设置里直接添加 apache的话 直接在项目文件里添加.htaccess文件 会考虑参照宝塔面板 把常用的rewrite规则列出来 直接选择使用就行
