### ISSUE TITLE
m1 打开后 版本控制没有安装选项

### ISSUE THREAD

**Issue by askofcc** [xpf0000/PhpWebStudy#23]
如题 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/44773069/199410748-6ed88f84-d03a-483e-8d5e-f210ea25c373.png">

**Comment by xpf0000** [comment]
这个是没有检测到php相关版本信息, 应该是电脑环境的问题, 建议执行下brew info php看下, 如果显示不正常的话, 建议重装brew
https://www.phpwebstudy.com/help-4-2.html

**Comment by askofcc** [comment]
核对过了 是brew 环境有问题 重装一下就好了
