### ISSUE TITLE
Http Serve外网问题

### ISSUE THREAD

**Issue by dcto** [xpf0000/PhpWebStudy#25]
Http Serve功能，监听地址不应该是 localhost , 否则外部无法访问

**Comment by xpf0000** [comment]
这里显示的是localhost, 但是实际上用ip也是可以访问的,  用IP加端口号就行了

**Comment by dcto** [comment]
> 这里显示的是localhost, 但是实际上用ip也是可以访问的, 用IP加端口号就行了

有可能是我macOS的防火墙问题，同局域网暂时无法访问， 我检查一下吧，   windows暂时还没测试。
