### ISSUE TITLE
PhpWebStudy很好用，强烈支持推荐，提一点点后期优化功能

### ISSUE THREAD

**Issue by byphp-com** [xpf0000/PhpWebStudy#27]
换mac后没有便捷的套件环境，所以直接一直使用docker来开发。
最近发现PhpWebStudy，这个对于mac上开发php来说，真的是太好用了。
已推荐他人使用，支持！

希望后面能有更好的优化得更好。
个人习惯把程序界面退出，但是程序别退了，然后希望把图标加到菜单栏，点击图标会有快捷启动,关闭，打开主界面便捷功能等。
然后希望tools可以做成插件，让大家一起贡献。FeHelper这个插件里面的功能都是非常合适复写的，好用。

**Comment by xpf0000** [comment]
感谢支持 ^_^
最新版已添加系统托盘功能, 可以下载更新看看
