### ISSUE TITLE
php多版本的时候，终端命令执行php的时候希望可以能指定版本

### ISSUE THREAD

**Issue by byphp-com** [xpf0000/PhpWebStudy#28]
比如我安装了
PHP7.3
PHP7.4
PHP8.2

然后项目终端命令php start.php的时候是以PHP7.4去执行的，现在好像是以最后安装的那个版本。
如果可以在PhpWebStudy里能指定版本，或者可以设置多个
php73 start.php
php74 start.php
php82 start.php

以及默认指定的php start.php

然后现在卸载掉默认的PHP版本后，执行php命令会提示“command not found: php”
自己手动设置才可以

`brew link --overwrite --force php@7.4
`

还有一个问题，安装多个php版本后，我重启php会有起不来的情况。
An another FPM instance seems to already listen on /tmp/phpwebstudy-php-cgi-82.sock

**Comment by xpf0000** [comment]
最新版已修复PHP启动问题, 已添加可以设定某个版本为系统全局版本的功能
