### ISSUE TITLE
不支持macos 13.1 / Intel平台?

### ISSUE THREAD

**Issue by xiusin** [xpf0000/PhpWebStudy#29]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/36065131/218426701-aff5e4f6-8764-43e2-8080-b1fbd045519b.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/36065131/218426839-4c0ed93d-68b0-4cc8-a9f7-21d2aeeebbbb.png">

**Comment by xpf0000** [comment]
intel和Apple M安装包已经分开了, 带arm64的适用于Apple M, 不带的适用于intel, 注意不要下错了

**Comment by xiusin** [comment]
@xpf0000 好吧, 刚才看到arm的包
