### ISSUE TITLE
新版本切换PHP

### ISSUE THREAD

**Issue by HelplessMan** [xpf0000/PhpWebStudy#33]
更新新版本后，PHP可以同时启动2个版本的吗？设置全局切换也不管用。。 话说如果同时启动多个版本。具体是使用那个版本？

另外单独设置一个全局版本的话。感觉只有命令行生效了(因为以前那种切换方式, 例如我 php8.1的安装了扩展， 8.0的没安装。如果在使用的时候出错了我就知道当前是用的那个版本的。现在更新后，切换了8.1 ，命令行变了。但是 nginx这里没有变)

**Comment by xpf0000** [comment]
1. 现在可以同时启动多个版本
2. 新版本需要设定每个站点使用的php版本
3. 程序里php启动的是php-fpm,  只有站点用了某个版本, 这个版本才会实际处理php解析,  命令行用的是php命令, 和php-fpm无关
4. 设置全部版本就是设置环境变量里的php执行命令的版本, 和php-fpm无关, 看你全局PHP想用哪个版本就设置哪个版本

**Comment by HelplessMan** [comment]
> 1. 现在可以同时启动多个版本
> 2. 新版本需要设定每个站点使用的php版本
> 3. 程序里php启动的是php-fpm,  只有站点用了某个版本, 这个版本才会实际处理php解析,  命令行用的是php命令, 和php-fpm无关
> 4. 设置全部版本就是设置环境变量里的php执行命令的版本, 和php-fpm无关, 看你全局PHP想用哪个版本就设置哪个版本

看到第2条明白了。其实以前在php那里切换版本的功能是针对全局的，现在修改成了针对某一个网站了？
刚才在host里面看到可以切换版本的选项了。设置后的确起到了以前的那个作用了。
感谢～ 功能越来越完善了。。 强力推荐身边朋友了。。 哈哈


另外就是有没有考虑弄一个frp的功能?

**Comment by xpf0000** [comment]
感谢支持, 多帮忙推荐下, 用的人多了, 功能才会越来越完善, frp会考虑下, 等后续更新吧

**Comment by HelplessMan** [comment]
好的好的， 好东西必须推荐。。希望越来越完善了哈～
