### ISSUE TITLE
mongo安装使用失败

### ISSUE THREAD

**Issue by ypf138199209** [xpf0000/PhpWebStudy#39]
![WX20230418-110715@2x](https://user-images.githubusercontent.com/20056143/232661944-43cc7c5e-22cd-4abf-8138-7d4d9179aa8f.png)
![WX20230418-111351@2x](https://user-images.githubusercontent.com/20056143/232662069-58a8d436-7a26-4831-ac2c-61b60eca244b.png)
![WX20230418-110807@2x](https://user-images.githubusercontent.com/20056143/232662102-aa6665b0-99a7-47b3-b814-504cfcfbe09b.png)

**Comment by xpf0000** [comment]
最新版已处理
