### ISSUE TITLE
请问命令行的php -v版本和composer对应的php版本这块如何适配

### ISSUE THREAD

**Issue by MRchenao** [xpf0000/PhpWebStudy#40]

**Comment by xpf0000** [comment]
PHP管理里, 可以把某个版本设置成系统全局版本,  设置完后, 系统终端里, php 指向的就是设定的版本, 前提是自己没有在系统环境变量里设置PHP环境, 你composer需要用哪个版本, 就设置哪个版本为系统全局版本

**Comment by MRchenao** [comment]
您好，邮件已收到，我将在阅读邮件后，尽快给您回复！
