### ISSUE TITLE
如果不同的站点可以使用不同的端口就好了。

### ISSUE THREAD

**Issue by xiaohu8728** [xpf0000/PhpWebStudy#41]
比如：http://www.test1.com:8081
           http://www.test2.com:8082

**Comment by xiaohu8728** [comment]
为什么我不行呀？一个8080 一个8081 结果8081端口没打开。

**Comment by xpf0000** [comment]
你用的apache吧, apache比较麻烦, 端口必须Listen, 然后还不能重复, 例如 apache本身的配置文件中Listen了8080, 站点的vhost文件中就不能再有Listen 8080,  多端口建议使用nginx, 无需额外配置, 直接就可用
