### ISSUE TITLE
Mysql / Redis 等扩展如何修改为使用本地 Docker 已经安装好的

### ISSUE THREAD

**Issue by hgx** [xpf0000/PhpWebStudy#42]

**Comment by hgx** [comment]
能否使用我现有的这些
![image](https://user-images.githubusercontent.com/34025950/236721150-cd8acc1c-fc73-4537-a4ee-1321a1b63e91.png)

**Comment by xpf0000** [comment]
1. phpwebstudy设置里可以选择某个软件的自定义安装位置, 会自动识别, 识别到后就可以在 phpwebstudy里管理服务, 启动/重启等, 但是不确定docker是否对外暴露已安装的软件, 能从路径选择里选择到的话, 应该就没问题
2. 开发中, phpwebstudy可以和别的软件共用, 例如phpwebstudy启动nginx, php, docker启动mysql, redis, 彼此没有什么影响, 可以共用
