### ISSUE TITLE
版本管理不显示可以下载的版本

### ISSUE THREAD

**Issue by yi4396** [xpf0000/PhpWebStudy#43]
系统版本：MacOS M1  13.3.1
安装ARM版本的APP，打开之后 
Nginx只展示本地之前通过brew安装的1.23.4的版本；
切换到PHP，展示了之前安装的7.4和8.2版本，版本管理tab一直转圈，显示：可用版本获取中...
切换到MongoDB，本地之前没有安装，版本管理一直转圈，显示：可用版本获取中...

**Comment by yi4396** [comment]
人在国外，应该可以排除网络问题。

**Comment by xpf0000** [comment]
https://www.macphpstudy.com/zh/help-0-1.html

**Comment by yi4396** [comment]
经过尝试  应该是和用了ExpressVPN代理有关  。。。
