### ISSUE TITLE
PhpWebStudy 正常运行，重启动后，读不所有安装软件，不能正常运行

### ISSUE THREAD

**Issue by dysibai** [xpf0000/PhpWebStudy#44]
PhpWebStudy 正常运行，重启动后，读不所有安装软件，不能正常运行！我本机已安装php,nginx,mysql 先前正常工作

**Comment by dysibai** [comment]
![Uploading 截屏2023-05-16 下午2.44.54.png…]()

**Comment by xpf0000** [comment]
命令行 看下brew环境是否正常, which brew,  brew --repo,  brew --cellar,  所有安装软件都无法读取应该是软件没识别到系统brew环境

**Comment by dysibai** [comment]
brew是正常的。但是已经安装的一些工具，无法使用
