### ISSUE TITLE
软件出现重复的 php版本和报错

### ISSUE THREAD

**Issue by woden234** [xpf0000/PhpWebStudy#51]
mac m1 电脑 phpwebstudy软件出现重复的 php版本,有以下问题：
开启时报错
<img width="1421" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/16451600/ed9f43bc-e09f-4ec6-90f5-409fdfeb5b75">
关闭时也报错
<img width="1429" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/16451600/278028ff-4614-485f-ac56-a6dda2f1c173">

**Comment by xpf0000** [comment]
新版本已发布, 可以更新下试试
