### ISSUE TITLE
无法调用Redis

### ISSUE THREAD

**Issue by dysibai** [xpf0000/PhpWebStudy#52]
redis已安装，但是php   $redis = new redis();  程序直接死掉了

![截屏2023-09-09 下午5 23 45](https://github.com/xpf0000/PhpWebStudy/assets/131668725/b396f2b1-79b3-410b-89ca-5b767c4f5eb2)

**Comment by xpf0000** [comment]
php的redis扩展安装没? php的配置文件里启用redis扩展没?

**Comment by dysibai** [comment]
php的redis扩展安装了，扩展还有手工添加啊。。。。。。

**Comment by xpf0000** [comment]
> 

因为配置文件是完全开放的, 用户可以随意编辑. 如果程序里自动往配置文件里写东西, 可能会和用户自己编辑的内容冲突,  尽量是用户自己编辑配置文件,  扩展链接可以直接复制的, 复制粘贴保存就行了
