### ISSUE TITLE
如何自定义 port 安装的 PHP 版本的路径？

### ISSUE THREAD

**Issue by guanguans** [xpf0000/PhpWebStudy#53]
检测不到用 port 安装的 PHP。我尝试配置自定版本路径似乎也不管用。可否支持一下 port。

<img width="809" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/22309277/7d78b1ff-521f-4382-be60-18bba64b68c5">

**Comment by xpf0000** [comment]
最新版已经支持macports了, 不需要使用自定义路径. 
自定义路径只支持标准的文件结构, 例如自己编译的php等, 像macports这种把统一放到一个bin或者sbin里的, 识别不了

**Comment by guanguans** [comment]
@xpf0000 我刚试了下可以了，非常感谢🙏。
