### ISSUE TITLE
PHP 安装 redis 扩展报错

### ISSUE THREAD

**Issue by shijie1991** [xpf0000/PhpWebStudy#55]
安装扩展执行命令:
/Users/ xxxx/Library/PhpWebStudy/server/cache/php-redis.sh /Users/xxxx/Library/PhpWebStudy/server/cache /usr/local/Cellar/php/8.2.10/ 5.3.7 -x86_64 ****
如安装失败, 可尝试复制命令自行尝试安装
curl: option -C: expected a positive numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
1

**Comment by xpf0000** [comment]
新版已修复

**Comment by shijie1991** [comment]
6666
