### ISSUE TITLE
redis 多版本启动失败

### ISSUE THREAD

**Issue by shijie1991** [xpf0000/PhpWebStudy#56]
76553:C 25 Sep 2023 11:05:26.910 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
76553:C 25 Sep 2023 11:05:26.910 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=76553, just started
76553:C 25 Sep 2023 11:05:26.910 # Configuration loaded
76553:M 25 Sep 2023 11:05:26.911 * monotonic clock: POSIX clock_gettime
76553:M 25 Sep 2023 11:05:26.913 * Running mode=standalone, port=6379.
76553:M 25 Sep 2023 11:05:26.913 # Server initialized
76553:M 25 Sep 2023 11:05:26.913 # Can't handle RDB format version 11
76553:M 25 Sep 2023 11:05:26.913 # Fatal error loading the DB: Invalid argument. Exiting.

服务中 显示运行中

**Comment by xpf0000** [comment]
目前redis多版本公用一个配置文件, 配置文件设定的数据库存储文件是同一个, 多版本切换时, 会有这个问题, 后续会处理此问题
目前可以手动更改配置文件里的本地数据库路径来处理
```
#指定本地数据库路径
dir /Users/x/Library/PhpWebStudy/server/redis/common/db6
```
这里, 切换版本时, 改成版本单独的路径即可

**Comment by xpf0000** [comment]
新版本已处理, 新版本是单独的配置文件. 如果需要老版本的配置文件, 在配置文件界面, 点打开, 在打开的文件夹里 可以找到原来的配置文件
