### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by shijie1991** [xpf0000/PhpWebStudy#58]
每次 启动 提示 TypeError: Cannot read properties of null (reading 'split')

**Comment by xpf0000** [comment]
应用启动? 还是某个服务启动? 例如php, mysql

**Comment by shijie1991** [comment]
启动引用后

点击左上角 开关 启动服务 报错  TypeError: Cannot read properties of null (reading 'split')

**Comment by xpf0000** [comment]
单独启动每个服务试下, 看下是具体哪个服务报错, 群组启动现在不好判断问题出在哪
