### ISSUE TITLE
sg11 在Apple M2 Pro 不行呢

### ISSUE THREAD

**Issue by dysibai** [xpf0000/PhpWebStudy#60]
extension==../Cellar/php@7.4/7.4.33_2/pecl/20190902/ixed.dar 
已放在php.ini里面

**Comment by xpf0000** [comment]
extension=/usr/local/Cellar/php@7.4/7.4.33_4/pecl/20190902/ixed.dar

**Comment by xpf0000** [comment]
php扩展界面, 点sg11的复制链接, 把复制的链接添加到配置文件里

**Comment by dysibai** [comment]
我复制了，不行

**Comment by xpf0000** [comment]
php的配置文件里, 是否更改过扩展文件夹路径? php启动时, 错误信息发下
