### ISSUE TITLE
版本更新v1.2.0之后出现了502了

### ISSUE THREAD

**Issue by mezongzi** [xpf0000/PhpWebStudy#61]
<img width="1412" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/7627445/9910100f-0f3b-446b-af7e-f593423eca6d">
但是明明php是启动的状态哦
<img width="1158" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/7627445/a5b4ea16-719b-47f1-b585-1d97a39ecd31">

最后怎么解决的呢：需要手动启php-fpm74
<img width="719" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/7627445/8522aea2-6ae5-4d2a-a99e-596124150111">
我的电脑是： mac pro m2 max 16寸 96G内存

**Comment by xpf0000** [comment]
你没用软件的站点管理? 自己管理站点的话,  站点的vhost配置文件, 需要设置php解析

**Comment by mezongzi** [comment]
设置过的，不太行

徐鹏飞 ***@***.***> 于2023年11月15日周三 22:59写道：
