### ISSUE TITLE
hosts虚拟主机  过多  解析会很慢

### ISSUE THREAD

**Issue by hellowhwei** [xpf0000/PhpWebStudy#62]
hosts虚拟主机配置多了 解析会很慢 基本都在5s +

**Comment by xpf0000** [comment]
用的nginx还是apache？  虚拟主机大概有多少？ 虚拟主机使用ssl了吗？

**Comment by hellowhwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by hellowhwei** [comment]
> 使用的nginx还是apache？ 虚拟主机大概有多少？ 虚拟主机使用ssl了吗？

我之前加上 git仓库什么的转发 加上本身项目比较多大概有20几行吧  我从网上查到有人说大概14行以上就会解析的比较慢 我用的nginx
网上给出的解决方案是把常用域名放在前面  或者每行这样  127.0.0.1 localhost test.local 来代替 127.0.0.1 test.local
但是本项目好像每次都是把配置放在最后面的，我改了下次启动也会被覆盖掉

虚拟主机没用ssl

**Comment by xpf0000** [comment]
我这边本地测试了下， 大概38个站点， hosts里面大概60条记录， 未重现解析慢的情况， 你那边是否开启vpn？ 或者把 .local 的域名替换成 .com等其他后缀试试？
![001](https://github.com/xpf0000/PhpWebStudy/assets/12162162/306de645-2887-4c61-aa90-b17b4141be5e)
![002](https://github.com/xpf0000/PhpWebStudy/assets/12162162/8dde2e0b-ff9a-4c47-b7c1-434d2a924197)
![003](https://github.com/xpf0000/PhpWebStudy/assets/12162162/0ab5e343-6e90-48a9-a99e-f0861ee44038)

可以用curl 测试下 请求各个阶段的耗时， 看具体哪个阶段慢

`curl -o /dev/null -s -w 'dns_resolution: %{time_namelookup}\nconnect_time: %{time_connect}\nappconnect_time: %{time_appconnect}\npretransfer_time: %{time_pretransfer}\nstarttransfer_time: %{time_starttransfer}\ntotal_time: %{time_total}\n' http://xxxxxxxx`

**Comment by hellowhwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
