### ISSUE TITLE
所有模块的版本管理里面,一直显示可用版本获取中... 一直获取不到

### ISSUE THREAD

**Issue by zxyaust** [xpf0000/PhpWebStudy#66]
不管是否能翻墙,都是一直在获取可用版本,github访问肯定没问题的,打开测试过,检查新版本也能检查到
<img width="1019" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/16290254/d2b92a3f-7331-4983-8ab2-1cd59dacd196">
不论是php,nginx,mysql,等等,所有的都是如此

**Comment by zxyaust** [comment]
切换brew源,挨个试了一遍.都不行

**Comment by xpf0000** [comment]
命令行安装各个软件吧
brew search php

**Comment by zxyaust** [comment]
安装了macpots之后非常流畅,大赞

**Comment by zxyaust** [comment]
终于能轻松的mac php debug了
