### ISSUE TITLE
建议增加默认站内设置

### ISSUE THREAD

**Issue by itlaosiji** [xpf0000/PhpWebStudy#67]
建议增加设置默认站点
我设置默认站点后 这样我直接用我的内网IP访问的时候就会自动访问到默认站内。
这样我在不改NGINX的配置情况下就不需要把内网IP绑到站点上

**Comment by xpf0000** [comment]
逻辑上不可行。
nginx 和 apache 的虚拟站点配置文件， 是非动态的，写死的。 在访问站点时候， 也并不能干预 nginx 和 apache 对站点的处理。 设置默认站点， 唯一能行的操作就是设置某个站点的域名或者别名为 localhost， 但是这个操作并不具有唯一性， 其他站点也可以手动设置localhost或者内网 IP， 就会导致设置了也没用。
所以， 还是手动设置吧。

**Comment by itlaosiji** [comment]
在只考虑nginx的情况下如果在VHOST目录下建立一个文件单纯的来维护默认站点呢
如果改了。就会把默认站点的这个文件的defalut绑定的目录改一下就可以了。还有伪静态。
