### ISSUE TITLE
新版本的 brew 切换是不是有问题，一直加载不出来

### ISSUE THREAD

**Issue by bingxinti** [xpf0000/PhpWebStudy#69]
新版本的 brew 切换是不是有问题，一直加载不出来
我是 mac m3 电脑，本地命令行都正常可以
brew search 和 install 但是 phpwebstudy 里面死活不行。
我检查了 brew 也升级了，反复卸载了几次，软件里面就是不行。
软件里面还配置了代理，切换了多次多个源都不行。。

气死我了这情况。。。。。。

**Comment by xpf0000** [comment]
最新版已处理
