### ISSUE TITLE
phpwebstudy(nginx/php(7.2/7.3/7.4) 访问就是502

### ISSUE THREAD

**Issue by byphp-com** [xpf0000/PhpWebStudy#73]
这套是使用的ci，支持php7.2~7.4，然后从去年开始使用phpwebstudy开始就一直有502的问题。
```
#fastcgi都修改过
/tmp/phpwebstudy-php-cgi-72.sock
127.0.0.1:9000
```
都是这样，然后没办法使用phpwebstudy进行开发。

目前如果要修改或者开发这套程序还得再开docker部署宝塔开发的。**使用宝塔部署正常访问（php7.2~8.1都试过可以）**
刚好看到有人发的类似的问题，想请教一下这个怎么来定位问题，怎么解决呢？

**谢谢！**

下面是使用phpwebstudy启用访问产生的日志
```

nginx-access
127.0.0.1 - - [05/Mar/2024:15:08:50 +0900] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"

nginx-error
2024/03/05 15:08:50 [error] 21948#0: *6 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: dev1.local.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev1.local.test"

php-fpm日志
[05-Mar-2024 15:08:50] WARNING: [pool www] child 22202 exited on signal 11 (SIGSEGV) after 171.258840 seconds from start
[05-Mar-2024 15:08:50] NOTICE: [pool www] child 23009 started

redis
21390:M 05 Mar 2024 15:08:49.313 . 0 clients connected (0 replicas), 1030624 bytes in use
```

**Comment by xpf0000** [comment]
你加群了没?  QQ 群: 540738893   如果可以的话, 远程下帮你看看.  
如果不方便远程,  能否把你项目框架,  用到的 php 扩展发下, 我本次看看能否重现

**Comment by xpf0000** [comment]
Discord 也可以  https://discord.gg/E6vZDgm9

**Comment by xpf0000** [comment]
因为不清楚你CI的版本, 我在本地使用CI最新版测试的. 需要PHP7.4+.  未复现问题
怀疑是redis扩展和redis服务版本的问题, 导致php在调用redis扩展时, php cgi崩溃, 导致php-fpm重启   
先清空redis日志, 然后使用phpwebstudy启动项目. 可以看下redis日志里有没有类似Accepted 127.0.0.1:54190的语句. 如果没有, 说明php未能成功连接redis
如果使用的homebrew, 可以尝试 brew update && brew upgrade.  升级brew和软件包到最新版. 然后下载最新版phpwebstudy.  删除redis.so.  重新安装homebrew版本的扩展再试下

**Comment by itlaosiji** [comment]
502 多半是clash开了导致的。 关了就行了。
