### ISSUE TITLE
关于PHP7.4.33安装pdo_sqlsrv时的问题

### ISSUE THREAD

**Issue by suu1923** [xpf0000/PhpWebStudy#74]
2. pdo_sqlsrv扩展是区分PHP版本的, php版本小于7.0, pdo_sqlsrv扩展使用版本是3.0.1,php7.0-php7.2, pdo_sqlsrv扩展使用版本是4.3.0, php版本大于7.2, pdo_sqlsrv扩展使用版本是5.10.1

以上是文档上所说，但是我在本地安装好后，确是5.11.1

<img width="425" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/21141087/4c413d80-6837-4821-a3b6-d4fcd33350b2">
<img width="1100" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/21141087/944c8be2-47b5-4a6e-9dde-35a8b0c8aa41">

**Comment by xpf0000** [comment]
文档更新不及时, 官网文档后续会调整.  安装使用没啥问题就行
