### ISSUE TITLE
【已解决，请升级到v2.3.2】最新2.3.0版本更新后，编辑或新建站点保存一直在转圈

### ISSUE THREAD

**Issue by RobertZSun** [xpf0000/PhpWebStudy#75]
【本issue已解决】有问题的用户请升级到，当前v2.3.2问题已修复

----------

OS： MacOS 14.4 (23E214)

2.3.0之前的Version 2.2.5 没有任何问题，

升级后，编辑之前创建的站点，更改项目路径， 点击右上角保存，保存按钮一直在转圈，保存不上，

尝试删除这个站点，然后进行新建，新建的站点ssl证书都开启两个开关，ssl和自动管理证书，然后选择nginx 重写模板未 thinkphp，然后就还是保存不上，保存按钮在不停转圈

**Comment by xpf0000** [comment]
已发现问题, 等下发个更新

**Comment by xpf0000** [comment]
最新版已发布, 可以更新看下

**Comment by RobertZSun** [comment]
> 最新版已发布, 可以更新看下

我已经更新issue描述，告知后来人去更新到2.3.2版本，这个issue是否以及什么时候关闭你来决定吧，亦或给刚升级的大家展示一段时间
