### ISSUE TITLE
[BUG] Http Serve module was error working.

### ISSUE THREAD

**Issue by dcto** [xpf0000/PhpWebStudy#76]
Http Serve module, i'll  get an http ip with port
it's 

> http://localhost:61879/   http://10.11.162.228:61879/

But  when open this url in web browser get wrong web site. always redirect to  noratel.com  content

<img width="256" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/5618679/53e2fde8-068f-4dfb-9e71-0c4d8be53332">
<img width="573" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/5618679/00daca4e-2edb-42ad-8194-10ea83bda931">
<img width="640" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/5618679/526e0230-d29f-4071-99b6-0e04b2f09a69">
<img width="1684" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/5618679/3ef9bef0-8697-4c4b-a975-f038c5888d68">

**Comment by xpf0000** [comment]
This function simply uses the nodejs http module to start a web server. There is no complex logic.

This link, by default, points to index.html in the folder. You can check this by following these steps.

1. Look at index.html in the folder. See if the correct file is loaded.

2. use port kill in Tools. You can check the port number. See if any other web server is using it.

3. whether the DNS has been set by yourself

4. whether the global VPN is enabled.
