### ISSUE TITLE
扩展列表，没有 pdo， mysql 等

### ISSUE THREAD

**Issue by ctfang** [xpf0000/PhpWebStudy#77]

**Comment by xpf0000** [comment]
Homebrew安装的 php,  默认带的有.  无需额外安装.  

Macports安装的 php, 应该是有 mysql 的. pdo应该是自带的有.  

用户自定义安装的 php,  等待后续添加扩展支持吧

**Comment by ctfang** [comment]
检查目录是有 so 文件，忽略
