### ISSUE TITLE
安装pdo_sqlsrv报错

### ISSUE THREAD

**Issue by ctfang** [xpf0000/PhpWebStudy#78]
Cannot find config.m4. 
Make sure that you run '/usr/local/Cellar/php@5.6/5.6.40_9//bin/phpize' in the top level source directory of the module

**Comment by xpf0000** [comment]
已确认. macOS的官方扩展最低支持php7.0. 

7.0以下的, 扩展文件只有win的东西. 没有其他平台的.  

http://pecl.php.net/package/pdo_sqlsrv
