### ISSUE TITLE
Need Node

### ISSUE THREAD

**Issue by imyellow** [xpf0000/PhpWebStudy#80]
请问需要安装哪个Node版本才可以，启动服务时一直提示 Need Node，并且文件权限无法访问（目录已经`sudo chmod -R 755`），
<img width="993" alt="Snipaste_2024-04-01_13-17-34" src="https://github.com/xpf0000/PhpWebStudy/assets/3270774/91ea86ab-8d0f-4e44-8a94-0bf9b678daf5">

<img width="878" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/3270774/805e7f79-a7b3-477e-97b6-d6349311d732">

**Comment by xpf0000** [comment]
Need Node 是 DNS功能需要的. 如果不使用DNS 功能. 设置里隐藏 DNS.  如果使用, 需要系统里安装 nodejs.  node14以上都行.

站点文件夹不要放到系统目录.  放到桌面/下载/文稿等用户的文件夹.  文件夹权限不单单需要站点文件夹有权限. 还需要上层文件夹也有权限.  不需要手动执行 chmod.  创建站点时, 文件夹权限已自动处理过了.

**Comment by imyellow** [comment]
> Need Node 是 DNS功能需要的. 如果不使用DNS 功能. 设置里隐藏 DNS. 如果使用, 需要系统里安装 nodejs. node14以上都行.
> 
> 站点文件夹不要放到系统目录. 放到桌面/下载/文稿等用户的文件夹. 文件夹权限不单单需要站点文件夹有权限. 还需要上层文件夹也有权限. 不需要手动执行 chmod. 创建站点时, 文件夹权限已自动处理过了.

你好，感谢回复。

node系统有装的，版本16-20都切换过了，依旧不行。

文件夹在文稿的一个目录里，文稿在我自己当前的用户名下的，我也在设置里的 隐私与安全性 给PhpWebStudy赋予了完全磁盘访问权限，项目运行目录上层以及上上层都手动执行了 `sudo chmod -R 755`，站点也删除重新建立过，但依旧提示无权限。
是否需要给某个应用授权完全磁盘访问？


<img width="427" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/3270774/617f9641-6358-462d-844e-0c2a3206bf13">
![image](https://github.com/xpf0000/PhpWebStudy/assets/3270774/148cdce9-44e8-4d14-9541-effdd91f51ba)

<img width="480" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/3270774/ddbc4aa2-f4be-4c85-a47b-fe6454bb65b8">

**Comment by xpf0000** [comment]
程序里检测 node 环境的代码:
```
[ -s "$HOME/.bash_profile" ] && source "$HOME/.bash_profile";[ -s "$HOME/.zshrc" ] && source "$HOME/.zshrc";
```

如果你的node环境变量不在  ~/.bash_profile 或者 ~/.zshrc 这两个文件里, 或者从这两个文件, 无法获取到 node 环境. 就会识别失败. 

网站访问, PhpWebStudy不需要完全磁盘访问权限.  因为最终处理网站请求的是 apache/nginx/caddy.  先看下这几个的配置文件, 是否在配置文件里改过 user/group 等.  

也可以考虑使用标准的80/443端口. 使用.com 域名再试下.  

nginx的默认配置文件貌似自带 localhost,  可以试下屏蔽了再试下

**Comment by imyellow** [comment]
我用的是 Apache，配置文件里只改了 DocumentRoot 参数，其他没改动过。
我新增了一个.com的域名，更改了端口号，情况一样，提示 `you don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe`
另外该目录用MAMP的Apache可以正常跑起来运行。

我再次检查了配置，没有问题，~/.zshrc 里有对应的PATH，目录里也有node在，终端运行node也没有问题。
<img width="554" alt="image" src="https://github.com/xpf0000/PhpWebStudy/assets/3270774/cc46af02-a81f-41a2-8264-d205501d72d9">
