### ISSUE TITLE
macos 14.4.1系统Intel芯片点击菜单栏报错

### ISSUE THREAD

**Issue by canary920** [xpf0000/PhpWebStudy#81]
如题，电脑是13-inch, 2020, Four Thunderbolt 3 ports  系统：最新版14.4.1
点击菜单栏图标报错：
Error processing argument at index 0, conversion failure from

**Comment by xpf0000** [comment]
有没有截图? PHPWebStudy 哪个版本?

**Comment by canary920** [comment]
![CleanShot 2024-04-04 at 19 59 21@2x](https://github.com/xpf0000/PhpWebStudy/assets/7160801/53b2a778-dc94-40e6-862b-0e6522a49b07)

**Comment by canary920** [comment]
Version 2.4.2
