### ISSUE TITLE
Github Changes when adding a New Host

### ISSUE THREAD

**Issue by xcrap** [xpf0000/PhpWebStudy#85]
This was a bummer, I just realised when adding hosts (projects), It must make a change to the files because all files in each project gets modified and my GIT says there are changes in all the files (even they are exactly the same, maybe it change the modified date of something...). I don't know why this happen but I had to return to MAMP because of this, each time I added a new host all the files in that project shows modified in GIT, this made a mess with my working projects...

I can't use it with this issue, wonder if you have any idea why this happened.

All the best.

**Comment by xpf0000** [comment]
I checked the code again. I think I found the problem.

When user created the site, App wasn't sure if the permissions on the site's root directory were correct. The program tries to give the site directory 755 permissions. This resulted in a git change for the entire project.

This is a serious problem. I'll release an update to fix this as soon as possible. Thank you for your feedback.

**Comment by xpf0000** [comment]
I'm sorry about what happened to your program. It was my bad. I didn't realize how git was affected by file permission changes.

This has been fixed in the new version. APP will not attempt to fix file permissions again.

**Comment by xcrap** [comment]
It's all good, I've tested adding new hosts in the new version and it's not affected git so it's all good :)
Thanks for the quick fix!
