### ISSUE TITLE
mac 11.6 inter 安装存在问题？

### ISSUE THREAD

**Issue by sujiewen** [xpf0000/PhpWebStudy#87]
mac 11.6 inter 安装存在问题？安装nginx和mysql 一直卡在这里,下面是日志

# ------------------------------------------------------------------------------
Could not open file or uri for loading certificate to be updated from ../../../../test-runs/test_cmp_http/test.certout_newkey.pem: No such file or directory
cmp_main:apps/cmp.c:3384:CMP error: cannot set up CMP context
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_request_ctx:apps/cmp.c:1694:CMP warning: given -subject '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=leaf' overrides the subject of '../../../../test-runs/test_cmp_http/test.certout_newkey.pem' for KUR
../../../../util/wrap.pl ../../../../apps/openssl cmp -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd kur -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -out_trusted root.crt -oldcert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -server '[::1]:65259' => 1
    not ok 99 - kur certout overwriting oldcert
# ------------------------------------------------------------------------------
    #   Failed test 'kur certout overwriting oldcert'
    #   at test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
    # Looks like you failed 35 tests of 99.
not ok 5 - CMP app CLI Mock enrollment
# ------------------------------------------------------------------------------
# Looks like you failed 5 tests of 6.80-test_cmp_http.t ...................... 
Dubious, test returned 5 (wstat 1280, 0x500)

**Comment by xpf0000** [comment]
你开代理了?  看起来像是代理的问题.

**Comment by sujiewen** [comment]
我开代理了，前面都正常的

**Comment by sujiewen** [comment]
为什么一直卡在那里不动！

**Comment by sujiewen** [comment]
ia/L=Mountain View/O=Google Inc/CN=google.com' has expired
Warning: certificate from 'big_root.crt' with subject '/C=US/ST=California/L=Mountain View/O=Google Inc/CN=google.com' is not a CA cert
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending IR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: not enough data
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd ir -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_out_trusted_big.pem -out_trusted big_root.crt => 1
    not ok 61 - out_trusted bigcert
# ------------------------------------------------------------------------------
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_verification_ctx:apps/cmp.c:1230:CMP warning: -trusted option is ignored since -srvcert option is present
# setup_verification_ctx:apps/cmp.c:1234:CMP warning: -recipient option is ignored since -srvcert option is present
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending IR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: not enough data
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd ir -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_out_trusted5.pem -out_trusted issuing.crt -partial_chain -crl_check -srvcert server.crt => 1
    not ok 66 - out_trusted accept issuing ca cert even with CRL check enabled by default
# ------------------------------------------------------------------------------
Could not open file or uri for loading reference certificate (oldcert) from ../../../../test-runs/test_cmp_http/test.certout_newkey.pem: No such file or directory
cmp_main:apps/cmp.c:3384:CMP error: cannot set up CMP context
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd ir -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_oldcert.pem -out_trusted root.crt -oldcert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem => 1
    not ok 71 - oldcert ignored
# ------------------------------------------------------------------------------
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending IR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: not enough data
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd ir -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_csr1.pem -out_trusted root.crt -csr csr.pem => 1
    not ok 76 - pkcs10 converted to ir with privkey
# ------------------------------------------------------------------------------
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_request_ctx:apps/cmp.c:1659:CMP warning: -subject option is ignored for commands other than 'ir', 'cr', and 'kur' since sender is taken from -ref or -cert
# setup_request_ctx:apps/cmp.c:1671:CMP warning: -policies option is ignored for commands other than 'ir', 'cr', and 'kur'
# setup_request_ctx:apps/cmp.c:1757:CMP warning: -out_trusted option is ignored for 'p10cr', 'rr', and 'genm' commands
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending P10CR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: not enough data
# CMP error: transfer error:request sent: P10CR, expected response: CP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd p10cr -certout ../../../../test-runs/test_cmp_http/test.certout_p10cr.pem -out_trusted root.crt -csr csr.pem => 1
    not ok 80 - p10cr csr present
# ------------------------------------------------------------------------------
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending IR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: not enough data
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd ir -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_revreason.pem -out_trusted root.crt -revreason 5 => 1
    not ok 85 - ir + ignored revocation
# ------------------------------------------------------------------------------
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_client_ctx:apps/cmp.c:2220:CMP info: will contact http://127.0.0.1:50993/pkix/ via 127.0.0.1:7890 
# CMP info: sending CR
# CMP error: received error:code=502, reason=Bad Gateway
# CMP error: error receiving:server=http://127.0.0.1:50993 proxy=127.0.0.1:7890
# CMP error: transfer error:request sent: CR, expected response: CP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:50993' -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd cr -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_cr.pem -out_trusted root.crt => 1
    not ok 88 - cr
# ------------------------------------------------------------------------------
    #   Failed test 'cr'
    #   at test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
Could not open file or uri for loading CMP client certificate (optionally with chain) from ../../../../test-runs/test_cmp_http/test.certout_newkey.pem: No such file or directory
cmp_main:apps/cmp.c:3384:CMP error: cannot set up CMP context
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
../../../../util/wrap.pl ../../../../apps/openssl cmp -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd kur -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_kur.pem -out_trusted root.crt -oldcert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -server '[::1]:50993' -cert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -key new.key -extracerts issuing.crt => 1
    not ok 89 - kur explicit options
# ------------------------------------------------------------------------------
    #   Failed test 'kur explicit options'
    #   at test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
Could not open file or uri for loading CMP client certificate (optionally with chain) from ../../../../test-runs/test_cmp_http/test.certout_newkey.pem: No such file or directory
cmp_main:apps/cmp.c:3384:CMP error: cannot set up CMP context
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:apps/cmp.c:2571:CMP warning: -subject option argument is empty string, resetting option
# opt_str:apps/cmp.c:2571:CMP warning: -oldcert option argument is empty string, resetting option
# opt_str:apps/cmp.c:2571:CMP warning: -secret option argument is empty string, resetting option
../../../../util/wrap.pl ../../../../apps/openssl cmp -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd kur -subject "" -certout ../../../../test-runs/test_cmp_http/test.certout_kur_minimal.pem -oldcert "" -server '[::1]:50993' -cert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -key new.key -extracerts issuing.crt -secret "" => 1
    not ok 90 - kur minimal options
# ------------------------------------------------------------------------------
Could not open file or uri for loading certificate to be updated from ../../../../test-runs/test_cmp_http/test.certout_newkey.pem: No such file or directory
cmp_main:apps/cmp.c:3384:CMP error: cannot set up CMP context
# cmp_main:apps/cmp.c:3225:CMP info: using section(s) 'Mock enrollment' of OpenSSL configuration file '../Mock/test.cnf'
# setup_request_ctx:apps/cmp.c:1694:CMP warning: given -subject '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=leaf' overrides the subject of '../../../../test-runs/test_cmp_http/test.certout_newkey.pem' for KUR
../../../../util/wrap.pl ../../../../apps/openssl cmp -config ../Mock/test.cnf -section 'Mock enrollment' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '127.0.0.1:7890' -cmd kur -newkey new.key -newkeypass 'pass:' -certout ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -out_trusted root.crt -oldcert ../../../../test-runs/test_cmp_http/test.certout_newkey.pem -server '[::1]:50993' => 1
    not ok 99 - kur certout overwriting oldcert
# ------------------------------------------------------------------------------
    #   Failed test 'kur certout overwriting oldcert'
    #   at test/recipes/80-test_cmp_http.t line 151.
    #          got: '0'
    #     expected: '1'
    # Looks like you failed 35 tests of 99.
not ok 5 - CMP app CLI Mock enrollment
# ------------------------------------------------------------------------------
# Looks like you failed 5 tests of 6.80-test_cmp_http.t ...................... 
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/6 subtests 
80-test_cms.t ........................... ok
80-test_cmsapi.t ........................ ok
80-test_ct.t ............................ ok
80-test_dane.t .......................... ok
80-test_dtls.t .......................... ok
80-test_dtls_mtu.t ...................... ok
80-test_dtlsv1listen.t .................. ok
80-test_ocsp.t .......................... ok
80-test_pkcs12.t ........................ ok
80-test_policy_tree.t ................... ok
80-test_ssl_new.t ....................... ok
80-test_ssl_old.t ....................... ok
80-test_ssl_test_ctx.t .................. ok
80-test_sslcorrupt.t .................... ok
80-test_tsa.t ........................... ok
80-test_x509aux.t ....................... ok
81-test_cmp_cli.t ....................... ok

**Comment by sujiewen** [comment]
我代理正常的，不知道为什么在这个软件有问题

**Comment by xpf0000** [comment]
软件是通过 node 模拟系统环境然后执行 brew install/port install的.  毕竟不是真正的系统环境,和个人的电脑设置有关.

可以自行通过终端安装nginx/mysql 等. 安装完软件会自动识别.
