### ISSUE TITLE
Problems Installing XDebug

### ISSUE THREAD

**Issue by xcrap** [xpf0000/PhpWebStudy#88]
When installing XDebug this happens. It's been like this for over 10 minutes and nothing happens, now sure how to "debug" this issue. 

<img width="1517" alt="Screenshot 2024-06-05 at 11 43 56" src="https://github.com/xpf0000/PhpWebStudy/assets/828596/1965d83f-101b-4de4-97f3-0aa1ecf88b94">

**Comment by xpf0000** [comment]
sorry, but i also no idea for this issue.  Since the command already has -verbose added, brew already outputs the execution details.

You can copy the command and run it yourself in a terminal, and see if you get anything.

The first line in the log is the actual execution command

```
brew install —verbose shivammathur/extensions/xdebug@8.2
```

**Comment by xcrap** [comment]
Thanks I'll figure it out :)
