### ISSUE TITLE
安装服务失败,请看一下怎么解决,我百度了半天还是无法解决

### ISSUE THREAD

**Issue by ypf138199209** [xpf0000/PhpWebStudy#9]
redis-5.0.8 未安装,开始安装,请稍候...
Error: redis@5.0.8: Calling `cellar` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/redis@5.0.8.rb:9

安装失败

![image](https://user-images.githubusercontent.com/20056143/128609588-61bd87f4-a219-4493-8958-2bd74e7b5765.png)

按照错误提示,命令行:brew style --fix /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/redis@5.0.8.rb

![image](https://user-images.githubusercontent.com/20056143/128609888-576d49cf-1fea-4724-af30-8a988c241afd.png)

然后运行还是一样的报错,能是什么原因吗

**Comment by xpf0000** [comment]
新版已处理
