### ISSUE TITLE
Error: "User did not grant permission."

### ISSUE THREAD

**Issue by DevinKuehn** [xpf0000/PhpWebStudy#92]
Hi, first of all really nice app, it is really clean and easy to setup. I love it!

Nevertheless have a problem, i can't get it to work on Windows 11 Pro (22631.3737).

Whenever i try to start a service (except for DNS and FTP they start without problem) i get this toaster with "Error: User did not grant permission.".
![grafik](https://github.com/xpf0000/PhpWebStudy/assets/76881427/8a3d2803-076f-4968-bbd3-ca5d6badabdc)

There is nothing to be found regarding this problem in the logs.

And yes, i also tested it with admin privileges, but the same error.

**Comment by xianyunleo** [comment]
Please try this tool, it's also great

https://github.com/xianyunleo/EServer
